### ISSUE TITLE
Classname props

### ISSUE THREAD

**Issue by charjac** [tvkhoa/react-tippy#3]
Hello !
I am not able to customize the style of my tooltips netiher with className or style. Do you have any ideas why ?

**Comment by tvkhoa** [comment]
className and style is used for customizing the button ( the one will trigger the tooltip )
If you want to customize your tooltip in just few components, your can use `html` instead of `title`.

If you want to customize all tooltips, you can create your css theme as here 
 https://atomiks.github.io/tippyjs/#creating-themes

**Comment by charjac** [comment]
thanks for your quick answer, i will try the theming solution.

**Comment by tvkhoa** [comment]
I closed this issue here. I will add the doc in the next release. Thanks
